"""phase7 quality flags and pose context

Revision ID: 0d949ab8c0ec
Revises: 0f027c91b5db
Create Date: 2026-08-24 13:23:58.191958

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d949ab8c0ec'
down_revision: Union[str, None] = '0f027c91b5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_pose_context',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('persons', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_table('annotation_flags',
    sa.Column('annotation_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.Enum('CONE_NEAR_PLAYER', 'SUSPICIOUS_CONE', 'VERY_SMALL_CONE', 'LOW_CONFIDENCE', 'POSSIBLE_DUPLICATE', 'ISOLATED_DETECTION', 'TEMPORAL_ANOMALY', name='flag_type'), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('resolution', sa.Enum('CONFIRMED_FP', 'CONFIRMED_OK', 'EDITED', name='flag_resolution'), nullable=True),
    sa.Column('resolved_by', sa.String(length=200), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_flags_annotation_id'), 'annotation_flags', ['annotation_id'], unique=False)
    op.create_index(op.f('ix_annotation_flags_flag_type'), 'annotation_flags', ['flag_type'], unique=False)
    op.create_index(op.f('ix_annotation_flags_image_id'), 'annotation_flags', ['image_id'], unique=False)
    op.add_column('images', sa.Column('difficulty_components', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'difficulty_components')
    op.drop_index(op.f('ix_annotation_flags_image_id'), table_name='annotation_flags')
    op.drop_index(op.f('ix_annotation_flags_flag_type'), table_name='annotation_flags')
    op.drop_index(op.f('ix_annotation_flags_annotation_id'), table_name='annotation_flags')
    op.drop_table('annotation_flags')
    op.drop_table('image_pose_context')
    # ### end Alembic commands ###
