"""phase6 training jobs

Revision ID: 0f027c91b5db
Revises: dfc191cf7635
Create Date: 2026-08-24 12:54:39.989185

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f027c91b5db'
down_revision: Union[str, None] = 'dfc191cf7635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_jobs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('dataset_version_id', sa.UUID(), nullable=False),
    sa.Column('base_model_id', sa.UUID(), nullable=True),
    sa.Column('result_model_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Enum('LOCAL', 'KAGGLE', name='training_provider_type'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='training_job_status'), nullable=False),
    sa.Column('epochs', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('image_size', sa.Integer(), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=True),
    sa.Column('device', sa.String(length=20), nullable=False),
    sa.Column('current_epoch', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=200), nullable=True),
    sa.Column('kaggle_kernel_ref', sa.String(length=300), nullable=True),
    sa.Column('artifact_path', sa.String(length=1000), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_model_id'], ['models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_jobs_project_id'), 'training_jobs', ['project_id'], unique=False)
    op.create_table('training_job_epochs',
    sa.Column('training_job_id', sa.UUID(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('box_loss', sa.Float(), nullable=True),
    sa.Column('cls_loss', sa.Float(), nullable=True),
    sa.Column('dfl_loss', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('map50', sa.Float(), nullable=True),
    sa.Column('map50_95', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['training_job_id'], ['training_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_job_epochs_training_job_id'), 'training_job_epochs', ['training_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_job_epochs_training_job_id'), table_name='training_job_epochs')
    op.drop_table('training_job_epochs')
    op.drop_index(op.f('ix_training_jobs_project_id'), table_name='training_jobs')
    op.drop_table('training_jobs')
    # ### end Alembic commands ###
