"""phase3 annotation event log and projection

Revision ID: 22acb71306ab
Revises: da83a9aa9dcc
Create Date: 2026-08-24 12:13:54.137545

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22acb71306ab'
down_revision: Union[str, None] = 'da83a9aa9dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_events',
    sa.Column('annotation_id', sa.UUID(), nullable=False),
    sa.Column('revision_seq', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='annotation_event_action'), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('AUTO', 'HUMAN', 'CORRECTED', name='annotation_source'), nullable=False),
    sa.Column('error_category', sa.Enum('FALSE_POSITIVE', 'FALSE_NEGATIVE', 'WRONG_CLASS', 'BAD_BBOX', 'DUPLICATE', 'LOW_CONFIDENCE', 'OCCLUSION', 'BLUR', 'SMALL_OBJECT', name='error_category'), nullable=True),
    sa.Column('error_reason', sa.Enum('PLAYER_FOOT', 'PLAYER_SHOE', 'SHADOW', 'FOOTBALL', 'GRASS_BACKGROUND', 'OTHER', name='error_reason'), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_events_annotation_id'), 'annotation_events', ['annotation_id'], unique=False)
    op.create_index(op.f('ix_annotation_events_image_id'), 'annotation_events', ['image_id'], unique=False)
    op.create_table('annotations',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('AUTO', 'HUMAN', 'CORRECTED', name='annotation_source'), nullable=False),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='annotation_review_status'), nullable=False),
    sa.Column('latest_event_id', sa.UUID(), nullable=False),
    sa.Column('revision_seq', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_image_id'), 'annotations', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotations_image_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_annotation_events_image_id'), table_name='annotation_events')
    op.drop_index(op.f('ix_annotation_events_annotation_id'), table_name='annotation_events')
    op.drop_table('annotation_events')
    # ### end Alembic commands ###
