"""phase4 inference jobs table

Revision ID: bc98ace2f2dc
Revises: 22acb71306ab
Create Date: 2026-08-24 12:32:43.592808

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc98ace2f2dc'
down_revision: Union[str, None] = '22acb71306ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_jobs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='job_status'), nullable=False),
    sa.Column('conf', sa.Float(), nullable=False),
    sa.Column('iou', sa.Float(), nullable=False),
    sa.Column('total_images', sa.Integer(), nullable=False),
    sa.Column('processed_images', sa.Integer(), nullable=False),
    sa.Column('failed_images', sa.Integer(), nullable=False),
    sa.Column('total_predictions', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=200), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_jobs_dataset_id'), 'inference_jobs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_inference_jobs_project_id'), 'inference_jobs', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inference_jobs_project_id'), table_name='inference_jobs')
    op.drop_index(op.f('ix_inference_jobs_dataset_id'), table_name='inference_jobs')
    op.drop_table('inference_jobs')
    # ### end Alembic commands ###
