"""phase2 model registry

Revision ID: da83a9aa9dcc
Revises: 2013e8cfaf5d
Create Date: 2026-08-24 12:08:45.047560

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da83a9aa9dcc'
down_revision: Union[str, None] = '2013e8cfaf5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.Enum('DETECTOR', 'POSE', name='model_kind'), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('weights_path', sa.String(length=1000), nullable=False),
    sa.Column('class_config', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('base_model_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'projects', 'models', ['primary_model_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'projects', 'models', ['pose_model_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_table('models')
    # ### end Alembic commands ###
